# Generated by Django 4.1 on 2022-09-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='Site Name', max_length=255, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('projects_phases_template', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
