# Generated by Django 4.1 on 2022-08-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Developer', 'verbose_name_plural': 'Developers'},
        ),
    ]
