# Generated by Django 4.1 on 2022-08-07 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True, verbose_name='Birth Date')),
                ('phone', models.CharField(max_length=12, null=True, verbose_name='Phone Number')),
                ('mobile', models.CharField(max_length=12, null=True, verbose_name='Mobile Number')),
                ('nationality', django_countries.fields.CountryField(default='BH', max_length=2, null=True, verbose_name='Country')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2, null=True, verbose_name='Gender')),
                ('city', models.CharField(max_length=200, null=True, verbose_name='City')),
                ('address', models.TextField(null=True, verbose_name='Full Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
