# Generated by Django 4.1 on 2022-08-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Send Date')),
            ],
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
