# Generated by Django 4.1 on 2022-08-07 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.client')),
                ('is_company', models.BooleanField(default=False, verbose_name='Are you a Company?')),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=300, null=True, unique=True, verbose_name='Company Name')),
                ('web_site', models.URLField(blank=True, max_length=400, null=True, unique=True, verbose_name='Company Website')),
                ('trade_record', models.FileField(blank=True, null=True, upload_to='', verbose_name='Trade Record')),
            ],
            bases=('main_app.client',),
        ),
    ]
