# Generated by Django 4.1 on 2022-08-29 01:08

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainphase',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_phases', to='main_app.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=djgeojson.fields.PointField(),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='main_app.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='subphase',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_phases', to='main_app.mainphase', verbose_name='Sub Phase'),
        ),
        migrations.AlterField(
            model_name='subphaseupdate',
            name='sub_phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='main_app.subphase', verbose_name='Sub Phase Update'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main_app.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='updateattachment',
            name='update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main_app.subphaseupdate', verbose_name='Update Sun Phase'),
        ),
    ]
