# Generated by Django 4.1 on 2022-08-07 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Project Name')),
                ('summary', models.TextField(max_length=300, null=True, verbose_name='Summary')),
                ('type', models.CharField(choices=[('CO', 'Commercial'), ('RE', 'Residential'), ('IN', 'Industrial'), ('SP', 'Special Purpose'), ('LA', 'Lands')], default='CO', max_length=2, null=True, verbose_name='Type of the Project')),
                ('statue', models.CharField(choices=[('PL', 'Planing'), ('IN', 'Initial'), ('UC', 'Under Construction'), ('DO', 'Done'), ('RE', 'Ready To Use')], default='PL', max_length=2, null=True, verbose_name='The project Status')),
                ('location', models.TextField(null=True, verbose_name='Location')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Area in Square Meters')),
                ('stakeholders', models.TextField(blank=True, null=True, verbose_name='Project Stakeholders')),
                ('neighborhood', models.TextField(blank=True, null=True, verbose_name='Project Neighborhood')),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main_app.developer', verbose_name='Developer')),
            ],
        ),
    ]
