# Generated by Django 4.1 on 2022-08-08 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_phases', to='main_app.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='SubPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(null=True, verbose_name='Finish Date')),
                ('completion_date', models.DateTimeField(null=True, verbose_name='Duration')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_phases', to='main_app.mainphase', verbose_name='Sub Phase')),
            ],
        ),
        migrations.CreateModel(
            name='SubPhaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='Update Date')),
                ('description', models.TextField(null=True, verbose_name='Update Description')),
                ('sub_phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_phases_update', to='main_app.subphase', verbose_name='Sub Phase Update')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Attachment')),
                ('update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_sub_phases', to='main_app.subphaseupdate', verbose_name='Update Sun Phase')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateField(auto_now_add=True, verbose_name='Subscription Date')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main_app.client', verbose_name='Client')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main_app.project', verbose_name='Project')),
                ('referral_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Referral User')),
            ],
        ),
    ]
