# Generated by Django 4.1 on 2022-08-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_mainphase_subphase_subphaseupdate_updateattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Client Photo'),
        ),
    ]
