# Generated by Django 4.1 on 2022-09-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_project_address_alter_project_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
    ]
