# Generated by Django 4.1 on 2022-09-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_project_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('UR', 'Under Review'), ('P', 'Published'), ('HD', 'Hidden by the Developer'), ('HA', 'Hidden by he Admin')], default='UR', max_length=2, null=True, verbose_name='The project Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='statue',
            field=models.CharField(choices=[('PL', 'Planning'), ('IN', 'Initial'), ('UC', 'Under Construction'), ('DO', 'Done'), ('RE', 'Ready To Use')], default='PL', max_length=2, null=True, verbose_name='The project Status'),
        ),
    ]
