# Generated by Django 4.1 on 2022-09-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_project_visibility_alter_project_statue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stakeholders',
        ),
    ]
