# Generated by Django 4.1 on 2022-09-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_project_neighborhood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Area (Square Meters)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='statue',
            field=models.CharField(choices=[('PL', 'Planning'), ('IN', 'Initial'), ('UC', 'Under Construction'), ('DO', 'Done'), ('RE', 'Ready To Use')], default='PL', max_length=2, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('CO', 'Commercial'), ('RE', 'Residential'), ('IN', 'Industrial'), ('SP', 'Special Purpose'), ('LA', 'Lands')], default='CO', max_length=2, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('UR', 'Under Review'), ('P', 'Published'), ('HD', 'Hidden by the Developer'), ('HA', 'Hidden by he Admin')], default='UR', max_length=2, null=True, verbose_name='Visibility'),
        ),
    ]
